version: '3.4'
services:
  php:
    image: lucandrade/php-no-framework
    build:
      context: ./
    volumes:
      - ./:/code
    networks:
      - app
  http:
    image: nginx:1
    ports:
      - 8080:80
    volumes:
      - .//:/code
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/host.conf:/etc/nginx/sites-enabled/default
    depends_on:
      - php
    networks:
      - app
networks:
  app:
